# SEO Values
title: Denis' github page
tagline: A wannabe hacker page
description: A wannabe hacker page
url: https://dracula.github.io/gh-pages/
twitter: https://twitter.com/zenorocha
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Denis-REMACLE
  owner_url: https://github.com/Denis-REMACLE
  repository_url: https://github.com/Denis-REMACLE/denis-remacle.github.io

show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
